<a href="https://colab.research.google.com/github/KR720/Linux-study/blob/main/lec03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값 :\n",x)
  print("")

x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)


Type: <class 'numpy.ndarray'>
Shape: (3,)
값 :
 [1 2 3]

Type: <class 'numpy.ndarray'>
Shape: (3,)
값 :
 [5 2 3]



### rank가 2인 np 배열

In [6]:
y = np.array([[1,2],[4,5]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[1 2]
 [4 5]]



### rank가 2인 zero 로 만들어진 2차원 행렬

In [4]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[0. 0.]
 [0. 0.]]



### rank가 2인 one으로 만들어진 2차원 행렬

In [5]:
a = np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값 :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]



### rank가 2인 단위행렬(identity matrix)

In [7]:
a = np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값 :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



### 랜덤 행렬(0~1 사이 모든 값들이 나올 확률이 같음)

In [8]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값 :
 [[0.84320218 0.3525001  0.01465628 0.3793197 ]
 [0.21838625 0.67668633 0.55925943 0.55561826]
 [0.2535206  0.02347565 0.48096544 0.40697143]
 [0.25045304 0.71370445 0.1216559  0.9819465 ]]



### 랜덤 행렬(0을 평균으로 하는 가우시안 분포를 따르는 랜덤값)

In [9]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값 :
 [[ 0.08330935 -1.26539437  1.28191374 -0.61086071]
 [ 0.37745444  2.02639343  0.84861304  0.37103327]
 [-1.27223202  0.82221144  0.78592861 -0.33894776]
 [-0.29250622  0.82712733  0.19031072  1.31590029]]



### np array indexing

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값 :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



In [14]:
b = a[:2, 1:3]
print_val(b)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[2 3]
 [6 7]]



### 행렬의 n번째 행 얻기

In [15]:
row1 = a[1,:]
print_val(row1)

Type: <class 'numpy.ndarray'>
Shape: (4,)
값 :
 [5 6 7 8]



### 행렬의 원소별 연산


In [ ]:
m1 = np.array([1,2],[3,4], dtype = np.float64)
m1 = np.array([5,6],[7,8], dtype = np.float64)